name: isolate_rpc
description: Dart Isolate RPC. A simple RPC-style designed API to ease Isolate usage.
version: 1.1.3
repository: https://github.com/gaplo917/isolate_rpc
license: MIT
homepage: https://github.com/gaplo917/isolate_rpc

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  benchmark_harness: ^2.2.1
  collection: ^1.17.1
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  logging: ^1.1.1
